// home.js
export const HOME_FETCH_ALL_LIST = 'HOME_FETCH_ALL_LIST';
export const HOME_SET_ACTIVITY_PROJECT_LIST = 'HOME_SET_ACTIVITY_PROJECT_LIST';

// list.js
export const LIST_SET_ACTIVITY_PROJECT_LIST = 'LIST_SET_ACTIVITY_PROJECT_LIST';
